server:
  port: 10082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true
spring:
  zipkin:
    base-url: http://localhost:9999/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: project-mall